const Constant = {
    MAX_INPUT_HEIGHT:300,
    MESSAGE_PER_REFRESH:15,
    MESSAGE_STATE_SENDING:0,
    MESSAGE_STATE_SERVER_NOT_RECEIVE:1,
    MESSAGE_STATE_SERVER_RECEIVE:2,
    MESSAGE_STATE_TARGET_RECEIVE:3,
    MESSAGE_STATE_TARGET_READ:4,
    MESSAGE_TYEP_TEXT:0,
    MESSAGE_TYPE_IMAGE:1,
    MESSAGE_TYPE_FILE:2,
}

Object.freeze(Constant)
module.exports = Constant
